name: "Feature"

# @TODO redo all these triggers to be on check completed?
on:
  pull_request:
    branches:
      - "main" # only branches merging *into* main
      - "master"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  # run fast unit tests etc
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: env # just a dummy so some checks appear

  # Creates a GitHub "Deployment" record, which GH uses to populate the UI
  # and used as a trigger for Jenkins build
  dev-deployment:
    # run regardless of test result, but allow cancellation
    if: success() || failure()
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.github.com
    concurrency: dev
    steps:
      # - name: echo inputs
      #   id: debug_input
      #   uses: actions/github-script@v6
      #   with:
      #     result-encoding: string
      #     script: |
      #       return context
      # - name: Get result
      #   run: echo "${{ steps.debug_input.outputs.result.data }}"
      - name: Get Check Runs for related ref
        id: check_run
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const check = await github.rest.checks.listForRef({
              ref: "${{ github.sha }}",
              check_name: "unit-test",
              owner: "uktrade",
              repo: "temp-devops-test",
            });
            if (check.data.total_count < 1) {
              return "no run"
            }
            if (check.data.check_runs[0].status !== "completed") {
              return "incomplete"
            }
            return check.data.check_runs[0].conclusion
      - name: Get result
        run: echo "${{ steps.check_run.outputs.result }}"
      - name: Create GH Deployment for Dev environment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDeployment({
              environment: "dev",
              auto_merge: false,
              ref: "${{ github.event.pull_request.head.ref }}",
              description: "Auto Dev deployment",
              owner: context.repo.owner,
              repo: context.repo.repo,
              required_contexts: []
            })
