# Creates a GitHub "Deployment" record, which GH uses to populate the UI
name: "Production deploy"

concurrency: production

on:
  release:
    types:
      - "published"

jobs:
  # Creates a GitHub "Deployment" record, which GH uses to populate the UI
  # and used as a trigger for Jenkins build
  # We can add a manual approval step if we want
  deploy:
    if: ${{ github.event.ref.check-run.conclusion == "success" }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com
    steps:
      - name: Get Check Runs for related ref
        id: check_run
        uses: actions/github-script@v6
        with:
          script: |
            return github.rest.checks.listForRef({
              ref: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
      - name: Get result
        run: echo "${{steps.check_run.outputs.result.data.check_runs}}"
      - name: Create GH Deployment for PROD environment
        id: create_deployment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDeployment({
              environment: "production",
              auto_merge: false,
              ref: "${{ github.ref }}",
              description: "Release deployment",
              owner: context.repo.owner,
              repo: context.repo.repo,
              required_contexts: []
            })
