name: "Main"

# @TODO redo all these triggers to be on check completed?
on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  # run full test suite inc integration, e2e etc.
  full-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: env # just a dummy so some checks appear

  # Creates a GitHub "Deployment" record, which GH uses to populate the UI
  # and used as a trigger for Jenkins build
  staging-deployment:
    needs: full-test # only if tests pass
    if: success()
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.github.com
    concurrency: staging
    steps:
      - name: Create GH Deployment for Staging environment
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GH_TOKEN }}"
          script: |
            github.rest.repos.createDeployment({
              environment: "staging",
              auto_merge: false,
              ref: "${{ github.event.pull_request.base.ref }}",
              description: "Auto staging deployment",
              owner: context.repo.owner,
              repo: context.repo.repo,
              required_contexts: []
            })
