# Creates a GitHub "Deployment" record, which GH uses to populate the UI
name: "Release"

concurrency: production

on:
  release:
    types:
      - "published"

jobs:
  # Creates a GitHub "Deployment" record, which GH uses to populate the UI
  # and used as a trigger for Jenkins build
  # Only works if full testing has passed for this commit
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com
    steps:
      - name: Continue if this ref is fully tested
        id: check_run
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const check = await github.rest.checks.listForRef({
              ref: "${{ github.sha }}",
              check_name: "full-test",
              status: "completed",
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
            });
            if (check.data.total_count <= 0 || check.data.check_runs[0].conclusion != "success") {
              core.setFailed("No completed valid check runs found for that ref")
            }
            return "success"
      - name: Create GH Deployment for PROD environment
        id: create_deployment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDeployment({
              environment: "production",
              auto_merge: false,
              ref: "${{ github.ref }}",
              description: "Release deployment",
              owner: context.repo.owner,
              repo: context.repo.repo,
              required_contexts: []
            })
